### ISSUE TITLE
PHP on netlify

### ISSUE THREAD

**Issue by peppemete** [peppemete/peppemete.github.io#4]
How can I run the PHP on netlify? 
Because it still doesn't work, but the code is correct, because i tested it on an aruba server and it work.

**Comment by gorazd** [comment]
Here is how forms work on Netlify: https://docs.netlify.com/forms/setup/

You don't need PHP for this, PHP doesn't run on GitHub pages or Netlify.

**Comment by peppemete** [comment]
Fixed
