### ISSUE TITLE
Add scroll effect on single project page

### ISSUE THREAD

**Issue by peppemete** [peppemete/peppemete.github.io#5]
I would like to add this scroll effect: https://alvarotrigo.com/fullPage/#page1
Where i can find something to learn this effect?

**Comment by gorazd** [comment]
What part of your website would you use full page scroll on?

**Comment by peppemete** [comment]
The single project page (like Thefork and Magis), I already divided this page in sections and i would like to show one of these for each scroll.

**Comment by gorazd** [comment]
I would suggest you do a simple separate test first. Use these instructions:
https://github.com/alvarotrigo/fullPage.js/#including-files

Make a separate repository and add me as collaborator.

I checked and you can use this library for free is your portfolio is open sourced (it is if the repository is public) and you add a GPLv3 license to it.

**Comment by peppemete** [comment]
Thank you for your suggestion. More or less I understood how work this tool.
I did a page test, and I added you as collaborator, (https://github.com/peppemete/fullpage-test). Now I have another question, it is possible remove a JS script only for mobile?

**Comment by gorazd** [comment]
It's not the most simple or bulletproof thing to do.

Full-page has an option called `responsiveWidth`, it might be your solution:
https://github.com/alvarotrigo/fullPage.js#options

**Comment by peppemete** [comment]
Thank you, I solved using the option responsiveWidth:500 which disable the effect for the screen width < 500px
