### ISSUE TITLE
How can I use GET with JS?

### ISSUE THREAD

**Issue by peppemete** [peppemete/peppemete.github.io#7]
To make a small animation, when the user switches from the index to the contact or about, I inserted these 2 pages in the index and developed 2 JS functions that show the "desired page". Now the problem is in the nav because all 3 pages are in the same file (index). I thought of inserting a new function in the body using the onLoad action listener, which receives a value from GET and transforms the index into the desired page.
The question is: how can I move this value using GET, between 2 pages?

**Comment by gorazd** [comment]
Sorry I don't think i understand where the problem is.

The navigation work for me.

**Comment by peppemete** [comment]
Because i wanted to remove the other pages, and use only index, to show home-contact-about, i tryed to do this, and done it more or less (more less than more), but it's too difficult manage the animations keeping in mind, from the user from, and where he want go.
it exists another method to do animation between 2 pages?

**Comment by gorazd** [comment]
I understand, from pages like projects you go to index.html with all three links (home-contact-about).

You could:
- add anchor links (peppemete.github.io/#contact)
- use JS to check the URL (if it finds `#contact`)
- run the necessary function that contains the animation (`pageAnimation(contact);`)

Or try looking at a JS library:
https://github.com/swup/swup
